apiVersion: v1
kind: Service
metadata:
  name: node1
spec:
  selector:
    name: node1
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: node2
spec:
  selector:
    name: node2
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22

